### ISSUE TITLE
receiving { Error: EINVAL: invalid argument, read errno: -4071, code: 'EINVAL', syscall: 'read' }

### ISSUE THREAD

**Issue by vblain** [vekexasia/mysqldumpsplit#5]
Hi,

Just found your project and it would really solve a problem I'm having with being able to split a large dump file. Are you still supporting this branch ??

I'm currently getting the following error: { Error: EINVAL: invalid argument, read errno: -4071, code: 'EINVAL', syscall: 'read' } when trying to run the project. I do see that some libs are out of data, but currently can't take on updating the code myself.

**Comment by vekexasia** [comment]
Hey @vblain how are you launching the script?

**Comment by vblain** [comment]
installed globally. and run it from powershell against the dump.sql file.
no options set.

**Comment by cikal** [comment]
@vblain did your problem solved ?
i have same problem here, 3 days ago i using this tools in Ubuntu 16.04 with smooth and very well, but today im using this tools on Windows 7 with no luck..

**OS info** : Windows 7 (x86)
**NodeJS version** : v12.4.0
**npm version** : 6.9.0

**Problem** :
* After fresh install global CLI `npm install mysqldumpsplit -g`
* then i just run it with no options `mysqldumpsplit dummy_backup.sql`
* this **dummy_backup.sql** (_file size only 4,6 Gb_) less than 5 Gb, but another day in Ubuntu i has done split 24 Gb w/o problem using this amazing tools.. :cry: 

**Console Throw** :
```
Starting :)
[Error: EINVAL: invalid argument, read] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'read'
}
```

@vekexasia can you help to fix it ?
thanks

**Comment by cikal** [comment]
Try another way, with clone this repo, and do `npm install` for all dep. these output from my command prompt, also i has :link:  attached log files from npm log.

maybe can help you for fixing this tools, again thanks for your time.

```
[2019-06-13T02_25_02_895Z-debug.log](https://github.com/vekexasia/mysqldumpsplit/files/3283888/2019-06-13T02_25_02_895Z-debug.log)
C:\Users\cikal\Desktop\mysqldumpsplit>npm install
npm WARN deprecated babel-preset-es2015@6.24.1: �  Thanks for using Babel: we re
commend using babel-preset-env now: please read https://babeljs.io/env to update
!
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, follo
wing the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try thi
s instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alterna
tives.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use
@segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install th
e latest version of pug instead of jade
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for comp
atibility with current and future versions of Node.js
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/f
ormatio instead
npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of
@sinonjs/samsam
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sur
e to switch over as this distribution is no longer supported and may contain bug
s and critical security issues.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated istanbul@0.3.22: This module is no longer maintained, try th
is instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alterna
tives.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and
 will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of
@sinonjs/samsam
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance
with the hapi support policy (hapi.im/support). Please upgrade to the latest ver
sion to get the best features, bug fixes, and security patches. If you are unabl
e to upgrade at this time, paid support is available for older versions (hapi.im
/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance
with the hapi support policy (hapi.im/support). Please upgrade to the latest ver
sion to get the best features, bug fixes, and security patches. If you are unabl
e to upgrade at this time, paid support is available for older versions (hapi.im
/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accorda
nce with the hapi support policy (hapi.im/support). Please upgrade to the latest
 version to get the best features, bug fixes, and security patches. If you are u
nable to upgrade at this time, paid support is available for older versions (hap
i.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sur
e to switch over as this distribution is no longer supported and may contain bug
s and critical security issues.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compa
tibility with current and future versions of Node.js
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, fl
atted is its successor.

> core-js@2.6.9 postinstall C:\Users\cikal\Desktop\mysqldumpsplit\node_modules\c
ore-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfill
ing JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Colle
ctive or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a goo
d job -)

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.

npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly
` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` fo
r more information.

> mysqldumpsplit@2.0.0 prepublish C:\Users\cikal\Desktop\mysqldumpsplit
> gulp

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
←[90m    at fs.js:27:26←[39m
    at req_ (C:\Users\cikal\Desktop\mysqldumpsplit\node_modules\←[4mnatives←[24m
\index.js:143:24)
    at Object.req [as require] (C:\Users\cikal\Desktop\mysqldumpsplit\node_modul
es\←[4mnatives←[24m\index.js:55:10)
    at Object.<anonymous> (C:\Users\cikal\Desktop\mysqldumpsplit\node_modules\←[
4mvinyl-fs←[24m\node_modules\←[4mgraceful-fs←[24m\fs.js:1:37)
←[90m    at Module._compile (internal/modules/cjs/loader.js:774:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10
)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:641:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:681:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:16:16)←[39m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mysqldumpsplit@2.0.0 prepublish: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mysqldumpsplit@2.0.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cikal\AppData\Roaming\npm-cache\_logs\2019-06-13T02_25_02_
895Z-debug.log

C:\Users\cikal\Desktop\mysqldumpsplit>
```
[2019-06-13T02_25_02_895Z-debug.log](https://github.com/vekexasia/mysqldumpsplit/files/3283904/2019-06-13T02_25_02_895Z-debug.log)

**Comment by ilantc** [comment]
I also encountered this issue, while debugging it I noticed that a negative start index is being send to `fs.read` on windows.
Adding `start = Math.max(start, 0);` to `readChunkOfFileToBuff` seems to solve this.
This is a dirty solution and I'm not sure what's the root cause, so didn't PR this, but this is possibly a quick fix to whoever will encounter this in the future :)
